CREATE TABLE IF NOT EXISTS `CAR` (
    `ID` INT AUTO_INCREMENT PRIMARY KEY,
    `BRAND_NAME` VARCHAR(100) NOT NULL,
    `MODEL_NAME` VARCHAR(100) NOT NULL,
    `REG_NO` VARCHAR(20) NOT NULL,
    `CAR_TYPE` VARCHAR(20) NOT NULL,
    `YR` INTEGER NOT NULL,
    `KMS` INTEGER NOT NULL,
    `PRICE` INTEGER NOT NULL
);